batis_crowdsourcing_homepage:
    path:     /
    defaults: { _controller: BatisCrowdsourcingBundle:Project:index }

batis_crowdsourcing_postjob:
    path:     /postjob
    defaults: { _controller: BatisCrowdsourcingBundle:Project:add }

batis_crowdsourcing_jobdetail:
    path:     /jobdetail/{id}
    defaults: { _controller: BatisCrowdsourcingBundle:Project:view }
    requirements:
      id: \d+
