services:
  batis_crowdsourcing.slugify:
    class: Batis\CrowdsourcingBundle\Slugify\BatisSlugify
#    batis_crowdsourcing.example:
#        class: Batis\CrowdsourcingBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
